### ISSUE TITLE
problem with images

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#271] opened 2018-05-03 13:42 UTC
> URL https://herencia.net/2018-05-02-jovenes-de-la-parroquia-de-herencia-premiados-por-la-asociacion-de-amigos-del-seminario/

![Image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46c1999b2487c1e5cdf9ad4cae58f3806b1c65262852f17b2087bb7ee8407a02575f4ead170e0941f8aa8839baa47e21d40854b088270a36d43703adbf881eba03bf238e4b8cb0bd894cc4fa70.png)

**Comment by DAreRodz** [comment] 2018-05-03 14:53
Caused by the same issue as #261. Now fixed.

**Closed by DAreRodz** 2018-05-03 14:53 UTC
Labels: MYR, bug, next
