### ISSUE TITLE
Some "robadobles" are cutted on rendering

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#297] opened 2018-05-21 17:34 UTC
The code of the robadoble that appears cutted is the following:

```
<div class="LazyLoad is-visible css-9cg72p e1wwt28c3" style="height: 600px; width: 300px;"><div id="ad33780_1_noticia_106803" width="300" height="600" class="css-1dm882o e1dxjsn0"><iframe id="sas_i33780" scrolling="no" frameborder="0" width="300" height="600" src="//www8.smartadserver.com/ac?nwid=1445&amp;siteid=78061&amp;pgid=881076&amp;fmtid=33780&amp;out=iframe&amp;async=1&amp;visit=s&amp;tmstp=202329644&amp;tgt=nullplatform%3Diphone&amp;orgfmtid=33780&amp;tag=ad33780_1_noticia_106803&amp;sh=667&amp;sw=375&amp;pgDomain=https%3A%2F%2Fwww.diariomotor.com%2Fcompeticion%2Fnoticia%2Fsebastien-loeb-logra-su-segundo-triunfo-en-el-world-rx-en-una-espectacular-final-en-mettet%2F&amp;noadcbk=sas.noad" style="margin: 0px; padding: 0px; width: 300px; height: 600px;"></iframe></div></div>
```

Let me know if we need more info in order to reproduce the issue.

**Comment by luisherranz** [comment] 2018-06-21 10:33
This doesn't look like our problem. My guess is that this problem is caused by SmartAd's "rich-media templates" loaded inside their "iframe" implementation. They have confirmed that they don't work.

We're going to give the option to load an ad with "std" implementation instead of "iframe". We should be really clear with the customers about "std" risks, but at least they'd have the option to turn it on and use "rich-media templates" or "dynamic height" ads.

I'll close this new because we can't reproduce it and we'll reopen it if we see this behaviour again once the new "std" implementation is available.

**Closed by luisherranz** 2018-06-21 10:33 UTC
Labels: DM, bug
